[package]
name = "salahtest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
islam = "0.2.0"
time = {git = "https://github.com/time-rs/time", branch = "main"}
